support buffers when mocking responses
jefflau/jest-fetch-mock pull request #223
Opened 2021-11-27 01:35 UTC by alexkolson

This would add support for the issue referenced in #218. This would be really useful for me and perhaps others as well! Let me know if this looks okay and/or if I should implement in a different way. Thanks!

2021-11-27 02:27 UTC, andreasg123 requested changes
To me, it looks like `responseWrapper` in `src/index.js` needs to be modified. That function creates a `Response` object via the constant `ActualResponse` that holds the JavaScript `Response` class. As the constructor for that class doesn't accept another `Response` object, the types of `body` and `response` in `responseWrapper` need to be checked to determine if that's already a `Response` object.

2021-11-27 02:27 UTC, andreasg123 commented on types/index.d.ts
> +export type MockResponseInitFunction = (request: Request) => MockResponseInit | string | Promise<MockResponseInit | string | Response>;
For symmetry, `Response` should also be acceptable without `Promise`.
```suggestion
export type MockResponseInitFunction = (request: Request) => MockResponseInit | string | Response | Promise<MockResponseInit | string | Response>;
```

2021-11-28 17:48 UTC, alexkolson commented
@andreasg123 Took another shot at it. What do you thnk?

2021-11-28 21:43 UTC, andreasg123 reviewed
It looks like this wasn't the correct place to check for `Response` after all. I believe that this change in `normalizeResponse` should do it:

```js
          return resp instanceof ActualResponse
            ? resp
            : typeof resp === 'string'
            ? responseWrapper(resp, init)
            : responseWrapper(resp.body, responseInit(resp, init))
```

2021-11-28 22:23 UTC, alexkolson commented
@andreasg123 Unfortunately if we swap out the check to go in `normalizeResponse` then it would have to be in two places no? Swapping the check to that location results in the test failing that checks that you can do:

```javascript
fetchMock.mockResponse(new Response('foo'))
```

I am perhaps missing something and welcome your continued feedback. Sorry if I wasn't able to grasp what you were talking about on the first try!

2021-11-28 23:23 UTC, andreasg123 commented
@alexkolson, I'm concerned about these cases:
```js
fetchMock.mockResponse(request => new Response('foo'));
fetchMock.mockResponse(request => Promise.resolve(new Response('foo')));
```
I don't think that those would work without the change that I suggested. For those examples, `isFn(bodyOrFunction)` in ` normalizeResponse` would be `true` whereas your example wouldn't take that path.

2021-11-28 23:26 UTC, andreasg123 commented
As `typeof resp === 'string'` would be `false`, a new `Response` object would be constructed from `resp.body`, losing all the other information in the original `Response` object.

2026-07-08 04:08 UTC, closed without merging

2026-07-08 04:08 UTC, jefflau commented
This shipped in master via #256, adapted to the current codebase with your tests and type overloads intact — thanks for the contribution and sorry it took so long to land. You're credited as co-author on the commit. It will go out to npm in 3.2.0.